name: Manual Workflow

on:
  workflow_dispatch:
    inputs:
      domain_name:
        description: 'Domain Name'
        required: true
        options: ['example.com', 'example.org', 'example.net']
      secret:
        description: 'Secret'
        required: true
        options: ['secret1', 'secret2', 'secret3']
      service_name:
        description: 'Service Name'
        required: true
        options: ['service1', 'service2', 'service3']

jobs:
  manual_input:
    runs-on: ubuntu-latest
    steps:
      - name: Use User Input
        id: user_input
        env:
          DOMAIN_NAME: ${{ github.event.inputs.domain_name }}
          SECRET: ${{ github.event.inputs.secret }}
          SERVICE_NAME: ${{ github.event.inputs.service_name }}
        run: |
          echo "Domain Name: $DOMAIN_NAME"
          echo "Secret: $SECRET"
          echo "Service Name: $SERVICE_NAME"

      - name: Hello World
        run: |
          echo "Hello, World! This is the $SERVICE_NAME service running at $DOMAIN_NAME using secret $SECRET."
